# Differential drive controller
type: "diff_drive_controller/DiffDriveController"
publish_rate: 30

left_wheel: 'front_left_wheel_joint'
right_wheel: 'front_right_wheel_joint'

# Odometry covariances for the encoder output of the robot. These values should
# be tuned to your robot's sample odometry data, but these values are a good place
# to start
pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

# Top level frame (link) of the robot description
base_frame_id: base_link

# Velocity and acceleration limits for the robot
linear:
  x:
    has_velocity_limits    : true
    max_velocity           : 0.2   # m/s
    has_acceleration_limits: true
    max_acceleration       : 0.6   # m/s^2
angular:
  z:
    has_velocity_limits    : true
    max_velocity           : 2.0   # rad/s
    has_acceleration_limits: true
    max_acceleration       : 6.0   # rad/s^2

# Gazebo PID controller parameters
#/gazebo_ros_control:
#  pid_gains:
#    front_left_wheel_joint:
#      p: 0.0
#      i: 0.0
#      d: 0.0
#    front_right_wheel_joint:
#      p: 0.0
#      i: 0.0
#      d: 0.0
